// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package main

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en": &dictionary{index: enIndex, data: enData},
		"ru": &dictionary{index: ruIndex, data: ruData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"Content":      1,
	"Name":         0,
	"Published at": 2,
	"Send":         4,
	"Tags":         3,
}

var enIndex = []uint32{ // 6 elements
	0x00000000, 0x00000005, 0x0000000d, 0x0000001a,
	0x0000001f, 0x00000024,
} // Size: 48 bytes

const enData string = "\x02Name\x02Content\x02Published at\x02Tags\x02Send"

var ruIndex = []uint32{ // 6 elements
	0x00000000, 0x00000011, 0x00000026, 0x00000044,
	0x0000004d, 0x00000060,
} // Size: 48 bytes

const ruData string = "" + // Size: 96 bytes
	"\x02Название\x02Содержимое\x02Дата публикации\x02Тэги\x02Отправить"

	// Total table size 228 bytes (0KiB); checksum: 36937515
